site_name: 2020_5DI_Team5
nav:
    - 'Project Charter': 'vspc.md'
    - 'Software Requirements Specification': 'srs.md'
    - 'Software Project Management Plan': 'spmp.md'
    - 'Project Canvas': 'elevatorSpeech.md'
    - 'Architecture and design': 'architecture_and_design.mdì
    - 'Iteration Plan': 'iteration_plan.md'
    - 'Memo of understanding': 'memo_of_understanding.md'
    - 'Project character': 'project_character.md'
    - 'Project succes criteria': 'project_success_criteria.md'
    - 'Release Plan': 'release_plan.md'
    - 'Software requirements': 'software_requirements_specification.md'
    - 'System documentation': 'system_documentation.md'
    - 'Test Case specification': 'test_case_specification.md'
    - 'Test Plan': 'test_plan.md'
    - 'User guide': 'user_guide.md'
    
theme:
    name: readthedocs

use_directory_urls: true
